
package java_api_testing.net_api.ws_testing.wsImpl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "JAXWS_WebServiceTesting_Server", targetNamespace = "http://ws_testing.net_api.java_api_testing/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JAXWSWebServiceTestingServer {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setMyTransferObject", targetNamespace = "http://ws_testing.net_api.java_api_testing/", className = "java_api_testing.net_api.ws_testing.wsImpl.SetMyTransferObject")
    @ResponseWrapper(localName = "setMyTransferObjectResponse", targetNamespace = "http://ws_testing.net_api.java_api_testing/", className = "java_api_testing.net_api.ws_testing.wsImpl.SetMyTransferObjectResponse")
    @Action(input = "http://ws_testing.net_api.java_api_testing/JAXWS_WebServiceTesting_Server/setMyTransferObjectRequest", output = "http://ws_testing.net_api.java_api_testing/JAXWS_WebServiceTesting_Server/setMyTransferObjectResponse")
    public void setMyTransferObject(
        @WebParam(name = "arg0", targetNamespace = "")
        MyTransferObject arg0);

    /**
     * 
     * @return
     *     returns java_api_testing.net_api.ws_testing.wsImpl.MyTransferObject
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMyTransferObject", targetNamespace = "http://ws_testing.net_api.java_api_testing/", className = "java_api_testing.net_api.ws_testing.wsImpl.GetMyTransferObject")
    @ResponseWrapper(localName = "getMyTransferObjectResponse", targetNamespace = "http://ws_testing.net_api.java_api_testing/", className = "java_api_testing.net_api.ws_testing.wsImpl.GetMyTransferObjectResponse")
    @Action(input = "http://ws_testing.net_api.java_api_testing/JAXWS_WebServiceTesting_Server/getMyTransferObjectRequest", output = "http://ws_testing.net_api.java_api_testing/JAXWS_WebServiceTesting_Server/getMyTransferObjectResponse")
    public MyTransferObject getMyTransferObject();

}
