/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netbeans_testing;

/**
 *
 * @author Lab119Alex
 */
public class LearningNetBeans03 extends javax.swing.JFrame {

    /**
     * Creates new form LearningNetBeans03
     */
    public LearningNetBeans03() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        trivial1 = new magicbeans.Trivial();
        numericField1 = new magicbeans.NumericField();
        numericField2 = new magicbeans.NumericField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NetBeans Testing 3");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        numericField1.setColumns(15);
        numericField1.setText("numericField1");
        numericField1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                numericField1PropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        getContentPane().add(numericField1, gridBagConstraints);

        numericField2.setColumns(15);
        numericField2.setText("numericField2");
        numericField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numericField2ActionPerformed(evt);
            }
        });
        numericField2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                numericField2PropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        getContentPane().add(numericField2, gridBagConstraints);

        jLabel1.setText("<html><table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" >\n   <tr align=\"center\">^<tr/><tr>Связанные свойства<tr/><tr align=\"center\">v<tr/></table>\n</html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        setSize(new java.awt.Dimension(266, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void numericField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numericField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numericField2ActionPerformed

    private void numericField1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_numericField1PropertyChange
        numericField2.setValue(numericField1.getValue());
    }//GEN-LAST:event_numericField1PropertyChange

    private void numericField2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_numericField2PropertyChange
        numericField1.setValue(numericField2.getValue());
    }//GEN-LAST:event_numericField2PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LearningNetBeans03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LearningNetBeans03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LearningNetBeans03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LearningNetBeans03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LearningNetBeans03().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private magicbeans.NumericField numericField1;
    private magicbeans.NumericField numericField2;
    private magicbeans.Trivial trivial1;
    // End of variables declaration//GEN-END:variables
}
