/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netbeans_testing;

/**
 *
 * @author Lab119Alex
 */
public class LearningNetBeans02 extends javax.swing.JFrame {

    /**
     * Creates new form LearningNetBeans02
     */
    public LearningNetBeans02() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        timer1 = new magicbeans.Timer();
        timer2 = new magicbeans.Timer();
        jPanel1 = new javax.swing.JPanel();
        molecule1 = new magicbeans.sunw.demo.molecule.Molecule();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();

        timer1.setDelay(100L);
        timer1.setRunning(false);
        timer1.addTimerListener(new magicbeans.TimerListener() {
            public void timerFired(magicbeans.TimerEvent evt) {
                timer1TimerFired(evt);
            }
        });

        timer2.setDelay(50L);
        timer2.setRunning(false);
        timer2.addTimerListener(new magicbeans.TimerListener() {
            public void timerFired(magicbeans.TimerEvent evt) {
                timer2TimerFired(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NetBeans Testing 2");

        jPanel1.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(molecule1, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<String> (new magicbeans.sunw.demo.molecule.MoleculeNameEditor().getTags())
        );
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        jToggleButton1.setText("Start/Stop Rotation");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton1);

        getContentPane().add(jPanel3, java.awt.BorderLayout.NORTH);

        setSize(new java.awt.Dimension(305, 276));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void timer1TimerFired(magicbeans.TimerEvent evt) {//GEN-FIRST:event_timer1TimerFired
        molecule1.rotateOnX();
    }//GEN-LAST:event_timer1TimerFired

    private void timer2TimerFired(magicbeans.TimerEvent evt) {//GEN-FIRST:event_timer2TimerFired
        molecule1.rotateOnY();
    }//GEN-LAST:event_timer2TimerFired

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        molecule1.setMoleculeName((String)jComboBox1.getSelectedItem());
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        timer1.setRunning(jToggleButton1.isSelected());
        timer2.setRunning(jToggleButton1.isSelected());
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LearningNetBeans02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LearningNetBeans02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LearningNetBeans02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LearningNetBeans02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LearningNetBeans02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton jToggleButton1;
    private magicbeans.sunw.demo.molecule.Molecule molecule1;
    private magicbeans.Timer timer1;
    private magicbeans.Timer timer2;
    // End of variables declaration//GEN-END:variables
}
